thisis = 0
tocheck = 0
ifyoucan = 0
handle = 0
collisions = 0
AdAdAdAdAdAdAdAd = 0
BCAdAdAdAdAdAdAd = 1
AdBCAdAdAdAdAdAd = 2
BCBCAdAdAdAdAdAd = 3
AdAdBCAdAdAdAdAd = 4
BCAdBCAdAdAdAdAd = 5
AdBCBCAdAdAdAdAd = 6
BCBCBCAdAdAdAdAd = 7
AdAdAdBCAdAdAdAd = 8
BCAdAdBCAdAdAdAd = 9
AdBCAdBCAdAdAdAd = 10
BCBCAdBCAdAdAdAd = 11
AdAdBCBCAdAdAdAd = 12
BCAdBCBCAdAdAdAd = 13
AdBCBCBCAdAdAdAd = 14
BCBCBCBCAdAdAdAd = 15
AdAdAdAdBCAdAdAd = 16
BCAdAdAdBCAdAdAd = 17
AdBCAdAdBCAdAdAd = 18
BCBCAdAdBCAdAdAd = 19
AdAdBCAdBCAdAdAd = 20
BCAdBCAdBCAdAdAd = 21
AdBCBCAdBCAdAdAd = 22
BCBCBCAdBCAdAdAd = 23
AdAdAdBCBCAdAdAd = 24
BCAdAdBCBCAdAdAd = 25
AdBCAdBCBCAdAdAd = 26
BCBCAdBCBCAdAdAd = 27
AdAdBCBCBCAdAdAd = 28
BCAdBCBCBCAdAdAd = 29
AdBCBCBCBCAdAdAd = 30
BCBCBCBCBCAdAdAd = 31
AdAdAdAdAdBCAdAd = 32
BCAdAdAdAdBCAdAd = 33
AdBCAdAdAdBCAdAd = 34
BCBCAdAdAdBCAdAd = 35
AdAdBCAdAdBCAdAd = 36
BCAdBCAdAdBCAdAd = 37
AdBCBCAdAdBCAdAd = 38
BCBCBCAdAdBCAdAd = 39
AdAdAdBCAdBCAdAd = 40
BCAdAdBCAdBCAdAd = 41
AdBCAdBCAdBCAdAd = 42
BCBCAdBCAdBCAdAd = 43
AdAdBCBCAdBCAdAd = 44
BCAdBCBCAdBCAdAd = 45
AdBCBCBCAdBCAdAd = 46
BCBCBCBCAdBCAdAd = 47
AdAdAdAdBCBCAdAd = 48
BCAdAdAdBCBCAdAd = 49
AdBCAdAdBCBCAdAd = 50
BCBCAdAdBCBCAdAd = 51
AdAdBCAdBCBCAdAd = 52
BCAdBCAdBCBCAdAd = 53
AdBCBCAdBCBCAdAd = 54
BCBCBCAdBCBCAdAd = 55
AdAdAdBCBCBCAdAd = 56
BCAdAdBCBCBCAdAd = 57
AdBCAdBCBCBCAdAd = 58
BCBCAdBCBCBCAdAd = 59
AdAdBCBCBCBCAdAd = 60
BCAdBCBCBCBCAdAd = 61
AdBCBCBCBCBCAdAd = 62
BCBCBCBCBCBCAdAd = 63
AdAdAdAdAdAdBCAd = 64
BCAdAdAdAdAdBCAd = 65
AdBCAdAdAdAdBCAd = 66
BCBCAdAdAdAdBCAd = 67
AdAdBCAdAdAdBCAd = 68
BCAdBCAdAdAdBCAd = 69
AdBCBCAdAdAdBCAd = 70
BCBCBCAdAdAdBCAd = 71
AdAdAdBCAdAdBCAd = 72
BCAdAdBCAdAdBCAd = 73
AdBCAdBCAdAdBCAd = 74
BCBCAdBCAdAdBCAd = 75
AdAdBCBCAdAdBCAd = 76
BCAdBCBCAdAdBCAd = 77
AdBCBCBCAdAdBCAd = 78
BCBCBCBCAdAdBCAd = 79
AdAdAdAdBCAdBCAd = 80
BCAdAdAdBCAdBCAd = 81
AdBCAdAdBCAdBCAd = 82
BCBCAdAdBCAdBCAd = 83
AdAdBCAdBCAdBCAd = 84
BCAdBCAdBCAdBCAd = 85
AdBCBCAdBCAdBCAd = 86
BCBCBCAdBCAdBCAd = 87
AdAdAdBCBCAdBCAd = 88
BCAdAdBCBCAdBCAd = 89
AdBCAdBCBCAdBCAd = 90
BCBCAdBCBCAdBCAd = 91
AdAdBCBCBCAdBCAd = 92
BCAdBCBCBCAdBCAd = 93
AdBCBCBCBCAdBCAd = 94
BCBCBCBCBCAdBCAd = 95
AdAdAdAdAdBCBCAd = 96
BCAdAdAdAdBCBCAd = 97
AdBCAdAdAdBCBCAd = 98
BCBCAdAdAdBCBCAd = 99
AdAdBCAdAdBCBCAd = 100
BCAdBCAdAdBCBCAd = 101
AdBCBCAdAdBCBCAd = 102
BCBCBCAdAdBCBCAd = 103
AdAdAdBCAdBCBCAd = 104
BCAdAdBCAdBCBCAd = 105
AdBCAdBCAdBCBCAd = 106
BCBCAdBCAdBCBCAd = 107
AdAdBCBCAdBCBCAd = 108
BCAdBCBCAdBCBCAd = 109
AdBCBCBCAdBCBCAd = 110
BCBCBCBCAdBCBCAd = 111
AdAdAdAdBCBCBCAd = 112
BCAdAdAdBCBCBCAd = 113
AdBCAdAdBCBCBCAd = 114
BCBCAdAdBCBCBCAd = 115
AdAdBCAdBCBCBCAd = 116
BCAdBCAdBCBCBCAd = 117
AdBCBCAdBCBCBCAd = 118
BCBCBCAdBCBCBCAd = 119
AdAdAdBCBCBCBCAd = 120
BCAdAdBCBCBCBCAd = 121
AdBCAdBCBCBCBCAd = 122
BCBCAdBCBCBCBCAd = 123
AdAdBCBCBCBCBCAd = 124
BCAdBCBCBCBCBCAd = 125
AdBCBCBCBCBCBCAd = 126
BCBCBCBCBCBCBCAd = 127
AdAdAdAdAdAdAdBC = 128
BCAdAdAdAdAdAdBC = 129
AdBCAdAdAdAdAdBC = 130
BCBCAdAdAdAdAdBC = 131
AdAdBCAdAdAdAdBC = 132
BCAdBCAdAdAdAdBC = 133
AdBCBCAdAdAdAdBC = 134
BCBCBCAdAdAdAdBC = 135
AdAdAdBCAdAdAdBC = 136
BCAdAdBCAdAdAdBC = 137
AdBCAdBCAdAdAdBC = 138
BCBCAdBCAdAdAdBC = 139
AdAdBCBCAdAdAdBC = 140
BCAdBCBCAdAdAdBC = 141
AdBCBCBCAdAdAdBC = 142
BCBCBCBCAdAdAdBC = 143
AdAdAdAdBCAdAdBC = 144
BCAdAdAdBCAdAdBC = 145
AdBCAdAdBCAdAdBC = 146
BCBCAdAdBCAdAdBC = 147
AdAdBCAdBCAdAdBC = 148
BCAdBCAdBCAdAdBC = 149
AdBCBCAdBCAdAdBC = 150
BCBCBCAdBCAdAdBC = 151
AdAdAdBCBCAdAdBC = 152
BCAdAdBCBCAdAdBC = 153
AdBCAdBCBCAdAdBC = 154
BCBCAdBCBCAdAdBC = 155
AdAdBCBCBCAdAdBC = 156
BCAdBCBCBCAdAdBC = 157
AdBCBCBCBCAdAdBC = 158
BCBCBCBCBCAdAdBC = 159
AdAdAdAdAdBCAdBC = 160
BCAdAdAdAdBCAdBC = 161
AdBCAdAdAdBCAdBC = 162
BCBCAdAdAdBCAdBC = 163
AdAdBCAdAdBCAdBC = 164
BCAdBCAdAdBCAdBC = 165
AdBCBCAdAdBCAdBC = 166
BCBCBCAdAdBCAdBC = 167
AdAdAdBCAdBCAdBC = 168
BCAdAdBCAdBCAdBC = 169
AdBCAdBCAdBCAdBC = 170
BCBCAdBCAdBCAdBC = 171
AdAdBCBCAdBCAdBC = 172
BCAdBCBCAdBCAdBC = 173
AdBCBCBCAdBCAdBC = 174
BCBCBCBCAdBCAdBC = 175
AdAdAdAdBCBCAdBC = 176
BCAdAdAdBCBCAdBC = 177
AdBCAdAdBCBCAdBC = 178
BCBCAdAdBCBCAdBC = 179
AdAdBCAdBCBCAdBC = 180
BCAdBCAdBCBCAdBC = 181
AdBCBCAdBCBCAdBC = 182
BCBCBCAdBCBCAdBC = 183
AdAdAdBCBCBCAdBC = 184
BCAdAdBCBCBCAdBC = 185
AdBCAdBCBCBCAdBC = 186
BCBCAdBCBCBCAdBC = 187
AdAdBCBCBCBCAdBC = 188
BCAdBCBCBCBCAdBC = 189
AdBCBCBCBCBCAdBC = 190
BCBCBCBCBCBCAdBC = 191
AdAdAdAdAdAdBCBC = 192
BCAdAdAdAdAdBCBC = 193
AdBCAdAdAdAdBCBC = 194
BCBCAdAdAdAdBCBC = 195
AdAdBCAdAdAdBCBC = 196
BCAdBCAdAdAdBCBC = 197
AdBCBCAdAdAdBCBC = 198
BCBCBCAdAdAdBCBC = 199
AdAdAdBCAdAdBCBC = 200
BCAdAdBCAdAdBCBC = 201
AdBCAdBCAdAdBCBC = 202
BCBCAdBCAdAdBCBC = 203
AdAdBCBCAdAdBCBC = 204
BCAdBCBCAdAdBCBC = 205
AdBCBCBCAdAdBCBC = 206
BCBCBCBCAdAdBCBC = 207
AdAdAdAdBCAdBCBC = 208
BCAdAdAdBCAdBCBC = 209
AdBCAdAdBCAdBCBC = 210
BCBCAdAdBCAdBCBC = 211
AdAdBCAdBCAdBCBC = 212
BCAdBCAdBCAdBCBC = 213
AdBCBCAdBCAdBCBC = 214
BCBCBCAdBCAdBCBC = 215
AdAdAdBCBCAdBCBC = 216
BCAdAdBCBCAdBCBC = 217
AdBCAdBCBCAdBCBC = 218
BCBCAdBCBCAdBCBC = 219
AdAdBCBCBCAdBCBC = 220
BCAdBCBCBCAdBCBC = 221
AdBCBCBCBCAdBCBC = 222
BCBCBCBCBCAdBCBC = 223
AdAdAdAdAdBCBCBC = 224
BCAdAdAdAdBCBCBC = 225
AdBCAdAdAdBCBCBC = 226
BCBCAdAdAdBCBCBC = 227
AdAdBCAdAdBCBCBC = 228
BCAdBCAdAdBCBCBC = 229
AdBCBCAdAdBCBCBC = 230
BCBCBCAdAdBCBCBC = 231
AdAdAdBCAdBCBCBC = 232
BCAdAdBCAdBCBCBC = 233
AdBCAdBCAdBCBCBC = 234
BCBCAdBCAdBCBCBC = 235
AdAdBCBCAdBCBCBC = 236
BCAdBCBCAdBCBCBC = 237
AdBCBCBCAdBCBCBC = 238
BCBCBCBCAdBCBCBC = 239
AdAdAdAdBCBCBCBC = 240
BCAdAdAdBCBCBCBC = 241
AdBCAdAdBCBCBCBC = 242
BCBCAdAdBCBCBCBC = 243
AdAdBCAdBCBCBCBC = 244
BCAdBCAdBCBCBCBC = 245
AdBCBCAdBCBCBCBC = 246
BCBCBCAdBCBCBCBC = 247
AdAdAdBCBCBCBCBC = 248
BCAdAdBCBCBCBCBC = 249
AdBCAdBCBCBCBCBC = 250
BCBCAdBCBCBCBCBC = 251
AdAdBCBCBCBCBCBC = 252
BCAdBCBCBCBCBCBC = 253
AdBCBCBCBCBCBCBC = 254
BCBCBCBCBCBCBCBC = 255
print AdAdAdAdAdAdAdAd
print BCAdAdAdAdAdAdAd
print AdBCAdAdAdAdAdAd
print BCBCAdAdAdAdAdAd
print AdAdBCAdAdAdAdAd
print BCAdBCAdAdAdAdAd
print AdBCBCAdAdAdAdAd
print BCBCBCAdAdAdAdAd
print AdAdAdBCAdAdAdAd
print BCAdAdBCAdAdAdAd
print AdBCAdBCAdAdAdAd
print BCBCAdBCAdAdAdAd
print AdAdBCBCAdAdAdAd
print BCAdBCBCAdAdAdAd
print AdBCBCBCAdAdAdAd
print BCBCBCBCAdAdAdAd
print AdAdAdAdBCAdAdAd
print BCAdAdAdBCAdAdAd
print AdBCAdAdBCAdAdAd
print BCBCAdAdBCAdAdAd
print AdAdBCAdBCAdAdAd
print BCAdBCAdBCAdAdAd
print AdBCBCAdBCAdAdAd
print BCBCBCAdBCAdAdAd
print AdAdAdBCBCAdAdAd
print BCAdAdBCBCAdAdAd
print AdBCAdBCBCAdAdAd
print BCBCAdBCBCAdAdAd
print AdAdBCBCBCAdAdAd
print BCAdBCBCBCAdAdAd
print AdBCBCBCBCAdAdAd
print BCBCBCBCBCAdAdAd
print AdAdAdAdAdBCAdAd
print BCAdAdAdAdBCAdAd
print AdBCAdAdAdBCAdAd
print BCBCAdAdAdBCAdAd
print AdAdBCAdAdBCAdAd
print BCAdBCAdAdBCAdAd
print AdBCBCAdAdBCAdAd
print BCBCBCAdAdBCAdAd
print AdAdAdBCAdBCAdAd
print BCAdAdBCAdBCAdAd
print AdBCAdBCAdBCAdAd
print BCBCAdBCAdBCAdAd
print AdAdBCBCAdBCAdAd
print BCAdBCBCAdBCAdAd
print AdBCBCBCAdBCAdAd
print BCBCBCBCAdBCAdAd
print AdAdAdAdBCBCAdAd
print BCAdAdAdBCBCAdAd
print AdBCAdAdBCBCAdAd
print BCBCAdAdBCBCAdAd
print AdAdBCAdBCBCAdAd
print BCAdBCAdBCBCAdAd
print AdBCBCAdBCBCAdAd
print BCBCBCAdBCBCAdAd
print AdAdAdBCBCBCAdAd
print BCAdAdBCBCBCAdAd
print AdBCAdBCBCBCAdAd
print BCBCAdBCBCBCAdAd
print AdAdBCBCBCBCAdAd
print BCAdBCBCBCBCAdAd
print AdBCBCBCBCBCAdAd
print BCBCBCBCBCBCAdAd
print AdAdAdAdAdAdBCAd
print BCAdAdAdAdAdBCAd
print AdBCAdAdAdAdBCAd
print BCBCAdAdAdAdBCAd
print AdAdBCAdAdAdBCAd
print BCAdBCAdAdAdBCAd
print AdBCBCAdAdAdBCAd
print BCBCBCAdAdAdBCAd
print AdAdAdBCAdAdBCAd
print BCAdAdBCAdAdBCAd
print AdBCAdBCAdAdBCAd
print BCBCAdBCAdAdBCAd
print AdAdBCBCAdAdBCAd
print BCAdBCBCAdAdBCAd
print AdBCBCBCAdAdBCAd
print BCBCBCBCAdAdBCAd
print AdAdAdAdBCAdBCAd
print BCAdAdAdBCAdBCAd
print AdBCAdAdBCAdBCAd
print BCBCAdAdBCAdBCAd
print AdAdBCAdBCAdBCAd
print BCAdBCAdBCAdBCAd
print AdBCBCAdBCAdBCAd
print BCBCBCAdBCAdBCAd
print AdAdAdBCBCAdBCAd
print BCAdAdBCBCAdBCAd
print AdBCAdBCBCAdBCAd
print BCBCAdBCBCAdBCAd
print AdAdBCBCBCAdBCAd
print BCAdBCBCBCAdBCAd
print AdBCBCBCBCAdBCAd
print BCBCBCBCBCAdBCAd
print AdAdAdAdAdBCBCAd
print BCAdAdAdAdBCBCAd
print AdBCAdAdAdBCBCAd
print BCBCAdAdAdBCBCAd
print AdAdBCAdAdBCBCAd
print BCAdBCAdAdBCBCAd
print AdBCBCAdAdBCBCAd
print BCBCBCAdAdBCBCAd
print AdAdAdBCAdBCBCAd
print BCAdAdBCAdBCBCAd
print AdBCAdBCAdBCBCAd
print BCBCAdBCAdBCBCAd
print AdAdBCBCAdBCBCAd
print BCAdBCBCAdBCBCAd
print AdBCBCBCAdBCBCAd
print BCBCBCBCAdBCBCAd
print AdAdAdAdBCBCBCAd
print BCAdAdAdBCBCBCAd
print AdBCAdAdBCBCBCAd
print BCBCAdAdBCBCBCAd
print AdAdBCAdBCBCBCAd
print BCAdBCAdBCBCBCAd
print AdBCBCAdBCBCBCAd
print BCBCBCAdBCBCBCAd
print AdAdAdBCBCBCBCAd
print BCAdAdBCBCBCBCAd
print AdBCAdBCBCBCBCAd
print BCBCAdBCBCBCBCAd
print AdAdBCBCBCBCBCAd
print BCAdBCBCBCBCBCAd
print AdBCBCBCBCBCBCAd
print BCBCBCBCBCBCBCAd
print AdAdAdAdAdAdAdBC
print BCAdAdAdAdAdAdBC
print AdBCAdAdAdAdAdBC
print BCBCAdAdAdAdAdBC
print AdAdBCAdAdAdAdBC
print BCAdBCAdAdAdAdBC
print AdBCBCAdAdAdAdBC
print BCBCBCAdAdAdAdBC
print AdAdAdBCAdAdAdBC
print BCAdAdBCAdAdAdBC
print AdBCAdBCAdAdAdBC
print BCBCAdBCAdAdAdBC
print AdAdBCBCAdAdAdBC
print BCAdBCBCAdAdAdBC
print AdBCBCBCAdAdAdBC
print BCBCBCBCAdAdAdBC
print AdAdAdAdBCAdAdBC
print BCAdAdAdBCAdAdBC
print AdBCAdAdBCAdAdBC
print BCBCAdAdBCAdAdBC
print AdAdBCAdBCAdAdBC
print BCAdBCAdBCAdAdBC
print AdBCBCAdBCAdAdBC
print BCBCBCAdBCAdAdBC
print AdAdAdBCBCAdAdBC
print BCAdAdBCBCAdAdBC
print AdBCAdBCBCAdAdBC
print BCBCAdBCBCAdAdBC
print AdAdBCBCBCAdAdBC
print BCAdBCBCBCAdAdBC
print AdBCBCBCBCAdAdBC
print BCBCBCBCBCAdAdBC
print AdAdAdAdAdBCAdBC
print BCAdAdAdAdBCAdBC
print AdBCAdAdAdBCAdBC
print BCBCAdAdAdBCAdBC
print AdAdBCAdAdBCAdBC
print BCAdBCAdAdBCAdBC
print AdBCBCAdAdBCAdBC
print BCBCBCAdAdBCAdBC
print AdAdAdBCAdBCAdBC
print BCAdAdBCAdBCAdBC
print AdBCAdBCAdBCAdBC
print BCBCAdBCAdBCAdBC
print AdAdBCBCAdBCAdBC
print BCAdBCBCAdBCAdBC
print AdBCBCBCAdBCAdBC
print BCBCBCBCAdBCAdBC
print AdAdAdAdBCBCAdBC
print BCAdAdAdBCBCAdBC
print AdBCAdAdBCBCAdBC
print BCBCAdAdBCBCAdBC
print AdAdBCAdBCBCAdBC
print BCAdBCAdBCBCAdBC
print AdBCBCAdBCBCAdBC
print BCBCBCAdBCBCAdBC
print AdAdAdBCBCBCAdBC
print BCAdAdBCBCBCAdBC
print AdBCAdBCBCBCAdBC
print BCBCAdBCBCBCAdBC
print AdAdBCBCBCBCAdBC
print BCAdBCBCBCBCAdBC
print AdBCBCBCBCBCAdBC
print BCBCBCBCBCBCAdBC
print AdAdAdAdAdAdBCBC
print BCAdAdAdAdAdBCBC
print AdBCAdAdAdAdBCBC
print BCBCAdAdAdAdBCBC
print AdAdBCAdAdAdBCBC
print BCAdBCAdAdAdBCBC
print AdBCBCAdAdAdBCBC
print BCBCBCAdAdAdBCBC
print AdAdAdBCAdAdBCBC
print BCAdAdBCAdAdBCBC
print AdBCAdBCAdAdBCBC
print BCBCAdBCAdAdBCBC
print AdAdBCBCAdAdBCBC
print BCAdBCBCAdAdBCBC
print AdBCBCBCAdAdBCBC
print BCBCBCBCAdAdBCBC
print AdAdAdAdBCAdBCBC
print BCAdAdAdBCAdBCBC
print AdBCAdAdBCAdBCBC
print BCBCAdAdBCAdBCBC
print AdAdBCAdBCAdBCBC
print BCAdBCAdBCAdBCBC
print AdBCBCAdBCAdBCBC
print BCBCBCAdBCAdBCBC
print AdAdAdBCBCAdBCBC
print BCAdAdBCBCAdBCBC
print AdBCAdBCBCAdBCBC
print BCBCAdBCBCAdBCBC
print AdAdBCBCBCAdBCBC
print BCAdBCBCBCAdBCBC
print AdBCBCBCBCAdBCBC
print BCBCBCBCBCAdBCBC
print AdAdAdAdAdBCBCBC
print BCAdAdAdAdBCBCBC
print AdBCAdAdAdBCBCBC
print BCBCAdAdAdBCBCBC
print AdAdBCAdAdBCBCBC
print BCAdBCAdAdBCBCBC
print AdBCBCAdAdBCBCBC
print BCBCBCAdAdBCBCBC
print AdAdAdBCAdBCBCBC
print BCAdAdBCAdBCBCBC
print AdBCAdBCAdBCBCBC
print BCBCAdBCAdBCBCBC
print AdAdBCBCAdBCBCBC
print BCAdBCBCAdBCBCBC
print AdBCBCBCAdBCBCBC
print BCBCBCBCAdBCBCBC
print AdAdAdAdBCBCBCBC
print BCAdAdAdBCBCBCBC
print AdBCAdAdBCBCBCBC
print BCBCAdAdBCBCBCBC
print AdAdBCAdBCBCBCBC
print BCAdBCAdBCBCBCBC
print AdBCBCAdBCBCBCBC
print BCBCBCAdBCBCBCBC
print AdAdAdBCBCBCBCBC
print BCAdAdBCBCBCBCBC
print AdBCAdBCBCBCBCBC
print BCBCAdBCBCBCBCBC
print AdAdBCBCBCBCBCBC
print BCAdBCBCBCBCBCBC
print AdBCBCBCBCBCBCBC
print BCBCBCBCBCBCBCBC